/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountantRouteImport } from './routes/accountant'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as FeePlansRouteImport } from './routes/fee-plans'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StudentRouteImport } from './routes/student'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as WhatsappRouteImport } from './routes/whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantRoute = AccountantRouteImport.update({
  id: '/accountant',
  path: '/accountant',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const FeePlansRoute = FeePlansRouteImport.update({
  id: '/fee-plans',
  path: '/fee-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accountant': typeof AccountantRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/batches': typeof BatchesRoute
  '/calendar': typeof CalendarRoute
  '/fee-plans': typeof FeePlansRoute
  '/fees': typeof FeesRoute
  '/notifications': typeof NotificationsRoute
  '/receipts': typeof ReceiptsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/student': typeof StudentRoute
  '/students': typeof StudentsRoute
  '/subscription': typeof SubscriptionRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accountant': typeof AccountantRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/batches': typeof BatchesRoute
  '/calendar': typeof CalendarRoute
  '/fee-plans': typeof FeePlansRoute
  '/fees': typeof FeesRoute
  '/notifications': typeof NotificationsRoute
  '/receipts': typeof ReceiptsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/student': typeof StudentRoute
  '/students': typeof StudentsRoute
  '/subscription': typeof SubscriptionRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accountant': typeof AccountantRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/batches': typeof BatchesRoute
  '/calendar': typeof CalendarRoute
  '/fee-plans': typeof FeePlansRoute
  '/fees': typeof FeesRoute
  '/notifications': typeof NotificationsRoute
  '/receipts': typeof ReceiptsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/student': typeof StudentRoute
  '/students': typeof StudentsRoute
  '/subscription': typeof SubscriptionRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accountant'
    | '/attendance'
    | '/auth'
    | '/batches'
    | '/calendar'
    | '/fee-plans'
    | '/fees'
    | '/notifications'
    | '/receipts'
    | '/reports'
    | '/settings'
    | '/student'
    | '/students'
    | '/subscription'
    | '/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accountant'
    | '/attendance'
    | '/auth'
    | '/batches'
    | '/calendar'
    | '/fee-plans'
    | '/fees'
    | '/notifications'
    | '/receipts'
    | '/reports'
    | '/settings'
    | '/student'
    | '/students'
    | '/subscription'
    | '/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/accountant'
    | '/attendance'
    | '/auth'
    | '/batches'
    | '/calendar'
    | '/fee-plans'
    | '/fees'
    | '/notifications'
    | '/receipts'
    | '/reports'
    | '/settings'
    | '/student'
    | '/students'
    | '/subscription'
    | '/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountantRoute: typeof AccountantRoute
  AttendanceRoute: typeof AttendanceRoute
  AuthRoute: typeof AuthRoute
  BatchesRoute: typeof BatchesRoute
  CalendarRoute: typeof CalendarRoute
  FeePlansRoute: typeof FeePlansRoute
  FeesRoute: typeof FeesRoute
  NotificationsRoute: typeof NotificationsRoute
  ReceiptsRoute: typeof ReceiptsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StudentRoute: typeof StudentRoute
  StudentsRoute: typeof StudentsRoute
  SubscriptionRoute: typeof SubscriptionRoute
  WhatsappRoute: typeof WhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant': {
      id: '/accountant'
      path: '/accountant'
      fullPath: '/accountant'
      preLoaderRoute: typeof AccountantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fee-plans': {
      id: '/fee-plans'
      path: '/fee-plans'
      fullPath: '/fee-plans'
      preLoaderRoute: typeof FeePlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountantRoute: AccountantRoute,
  AttendanceRoute: AttendanceRoute,
  AuthRoute: AuthRoute,
  BatchesRoute: BatchesRoute,
  CalendarRoute: CalendarRoute,
  FeePlansRoute: FeePlansRoute,
  FeesRoute: FeesRoute,
  NotificationsRoute: NotificationsRoute,
  ReceiptsRoute: ReceiptsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StudentRoute: StudentRoute,
  StudentsRoute: StudentsRoute,
  SubscriptionRoute: SubscriptionRoute,
  WhatsappRoute: WhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
